export const MESSAGE_TYPE = {
	DEVTOLLS_FLUSH_FOLDER_NODES: 'DEVTOLLS_FLUSH_FOLDER_NODES', //devtools刷新文件夹
	BACKGROUND_CREATE_PACK_TASK: 'BACKGROUND_CREATE_PACK_TASK', //background创建打包任务
	BACKGROUND_QUERY_TASK_STATUS: 'BACKGROUND_QUERY_TASK_STATUS', //background查询打包状态
	BACKGROUND_FLUSH_FOLDER_NODES: 'BACKGROUND_FLUSH_FOLDER_NODES', //background更新文件夹信息
	BACKGROUND_UPDATE_ACCESS_INFO: 'BACKGROUND_UPDATE_ACCESS_INFO', //background更新访问信息
	CONTENT_UPDATE_ACCESS_INFO: 'CONTENT_UPDATE_ACCESS_INFO', //content更新访问信息
	ping_background: 'ping_background',
} as const;

export type MESSAGE_TYPE_KEY = keyof typeof MESSAGE_TYPE;

export default MESSAGE_TYPE;
