export const MESSAGE_TYPE = {
	CREATE_PACK_TASK: 'CREATE_PACK_TASK',
	FLUSH_FOLDER_NODES: 'FLUSH_FOLDER_NODES',
	QUERY_TASK_STATUS: 'QUERY_TASK_STATUS',
	CREATE_PACK_TASK_RESULT: 'CREATE_PACK_TASK_RESULT',
	FLUSH_FOLDER_NODES_RESULT: 'FLUSH_FOLDER_NODES_RESULT',
	QUERY_TASK_STATUS_RESULT: 'QUERY_TASK_STATUS_RESULT',
} as const;

export default MESSAGE_TYPE;
